# Generated by Django 5.2.7 on 2025-10-21 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Student Currently Active?')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(choices=[('JR', 'Jr.'), ('SR', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('N', 'None')], default='N', max_length=10, verbose_name='Suffix')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Sex')),
                ('entering_grade_program', models.CharField(max_length=50, verbose_name='Entering Grade/Program')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='Mobile Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('recommended_by', models.CharField(blank=True, max_length=255, verbose_name='Who Recommended Us')),
                ('birth_country', models.CharField(max_length=100, verbose_name='Birth Country')),
                ('birth_city', models.CharField(max_length=100, verbose_name='Birth City')),
                ('birth_state', models.CharField(max_length=50, verbose_name='Birth State')),
                ('birth_zip', models.CharField(max_length=10, verbose_name='Birth Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Registering Parent/User')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAddress',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='home_address', serialize=False, to='api.student')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_history', serialize=False, to='api.student')),
                ('allergies', models.TextField(blank=True, verbose_name='Known Allergies (List)')),
                ('medications', models.TextField(blank=True, verbose_name='Current Medications and Dosages')),
                ('has_chronic_condition', models.BooleanField(default=False, verbose_name='Has Chronic Condition?')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Medical Notes')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('P1', 'Primary Parent'), ('P2', 'Secondary Parent')], default='P1', max_length=2, verbose_name='Parent Role')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffix')),
                ('mobile', models.CharField(max_length=15)),
                ('work_phone', models.CharField(blank=True, max_length=15, verbose_name='Work Phone')),
                ('work_ext', models.CharField(blank=True, max_length=10, verbose_name='Extension')),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=100)),
                ('is_employee', models.CharField(choices=[('E', 'Employee'), ('N', 'None/Self-Employed')], default='N', max_length=1, verbose_name='Employment Status')),
                ('employer_address', models.CharField(blank=True, max_length=255, verbose_name='Employer Address')),
                ('education_level', models.CharField(choices=[('HS', 'High School'), ('AA', 'Associate Degree'), ('BA', 'Bachelor Degree'), ('MA', 'Master Degree'), ('PHD', 'Doctorate'), ('OT', 'Other')], max_length=10, verbose_name='Education Level')),
                ('ssn', models.CharField(blank=True, max_length=11, verbose_name='SSN (Encrypted at Rest in Production)')),
                ('communication_preference', models.TextField(blank=True, verbose_name='Communication Preference')),
                ('address_is_different', models.BooleanField(default=False, verbose_name='Does this guardian live at a different address than the student?')),
                ('guardian_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_resident', to='api.guardianaddress')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='api.student')),
            ],
        ),
    ]
